//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecoratorPattern.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecoratorPattern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;People&gt;
        ///  &lt;Person Id=&quot;1&quot; FirstName=&quot;Amiee&quot; LastName=&quot;Avala&quot; EMail=&quot;Avala@antenatal.com&quot; /&gt;
        ///  &lt;Person Id=&quot;2&quot; FirstName=&quot;Mike&quot; LastName=&quot;Peer&quot; EMail=&quot;Peer@provoking.com&quot; /&gt;
        ///  &lt;Person Id=&quot;3&quot; FirstName=&quot;Shaniqua&quot; LastName=&quot;Soos&quot; EMail=&quot;Soos@step.com&quot; /&gt;
        ///  &lt;Person Id=&quot;4&quot; FirstName=&quot;Kary&quot; LastName=&quot;Kulesa&quot; EMail=&quot;Kulesa@kittens.com&quot; /&gt;
        ///  &lt;Person Id=&quot;5&quot; FirstName=&quot;Erna&quot; LastName=&quot;Fouty&quot; EMail=&quot;Fouty@epidermis.com&quot; /&gt;
        ///  &lt;Person Id=&quot;6&quot; FirstName=&quot;Soon&quot; LastName=&quot;Swailes&quot; EMail=&quot;Swailes@tallboy.com&quot; /&gt;
        ///  &lt;Per [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PeopleData {
            get {
                return ResourceManager.GetString("PeopleData", resourceCulture);
            }
        }
    }
}
